name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2

      - name: Install Packages
        run: make install

      - name: Format
        run: make format

      - name: Train
        run: make train

      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Update Branch
        env:
          USER_NAME: ${{ vars.USER_NAME }}
          USER_EMAIL: ${{ vars.USER_EMAIL }}
        run: make update-branch USER_NAME=$USER_NAME USER_EMAIL=$USER_EMAIL
